"""question likes

Revision ID: fdcdbc86db79
Revises: 6c7b48da76f2
Create Date: 2021-01-18 11:06:24.422801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdcdbc86db79'
down_revision = '6c7b48da76f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_likes',
    sa.Column('liker_id', sa.Integer(), nullable=True),
    sa.Column('liked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_likes')
    # ### end Alembic commands ###
